<?php

return [
    [
        'key'                               => 'field_5f1142e868e8b',
        'label'                             => 'text',
        'name'                              => 'text',
        'type'                              => 'text',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'placeholder'                       => '',
        'prepend'                           => '',
        'append'                            => '',
        'maxlength'                         => '',
    ],
    [
        'key'                               => 'field_5f1142ef68e8c',
        'label'                             => 'textarea',
        'name'                              => 'textarea',
        'type'                              => 'textarea',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'placeholder'                       => '',
        'maxlength'                         => '',
        'rows'                              => '',
        'new_lines'                         => '',
    ],
    [
        'key'                               => 'field_5f11438268e8d',
        'label'                             => 'number',
        'name'                              => 'number',
        'type'                              => 'number',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'placeholder'                       => '',
        'prepend'                           => '',
        'append'                            => '',
        'min'                               => '',
        'max'                               => '',
        'step'                              => '',
    ],
    [
        'key'                               => 'field_5f11438868e8e',
        'label'                             => 'range',
        'name'                              => 'range',
        'type'                              => 'range',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'min'                               => '',
        'max'                               => '',
        'step'                              => '',
        'prepend'                           => '',
        'append'                            => '',
    ],
    [
        'key'                               => 'field_5f11439368e8f',
        'label'                             => 'email',
        'name'                              => 'email',
        'type'                              => 'email',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'placeholder'                       => '',
        'prepend'                           => '',
        'append'                            => '',
    ],
    [
        'key'                               => 'field_5f11439c68e90',
        'label'                             => 'url',
        'name'                              => 'url',
        'type'                              => 'url',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'placeholder'                       => '',
    ],
    [
        'key'                               => 'field_5f1143a368e91',
        'label'                             => 'password',
        'name'                              => 'password',
        'type'                              => 'password',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'placeholder'                       => '',
        'prepend'                           => '',
        'append'                            => '',
    ],
    [
        'key'                               => 'field_5f1143ac68e92',
        'label'                             => 'image',
        'name'                              => 'image',
        'type'                              => 'image',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'return_format'                     => 'array',
        'preview_size'                      => 'medium',
        'library'                           => 'all',
        'min_width'                         => '',
        'min_height'                        => '',
        'min_size'                          => '',
        'max_width'                         => '',
        'max_height'                        => '',
        'max_size'                          => '',
        'mime_types'                        => '',
    ],
    [
        'key'                               => 'field_5f1143c468e93',
        'label'                             => 'file',
        'name'                              => 'file',
        'type'                              => 'file',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'return_format'                     => 'array',
        'library'                           => 'all',
        'min_size'                          => '',
        'max_size'                          => '',
        'mime_types'                        => '',
    ],
    [
        'key'                               => 'field_5f1143d968e94',
        'label'                             => 'wysiwyg',
        'name'                              => 'wysiwyg',
        'type'                              => 'wysiwyg',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
        'tabs'                              => 'all',
        'toolbar'                           => 'full',
        'media_upload'                      => 0,
        'delay'                             => 0,
    ],
    [
        'key'                               => 'field_5f1143e568e95',
        'label'                             => 'oembed',
        'name'                              => 'oembed',
        'type'                              => 'oembed',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'height'                            => '',
    ],
    [
        'key'                               => 'field_5f1143ee68e96',
        'label'                             => 'gallery',
        'name'                              => 'gallery',
        'type'                              => 'gallery',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'return_format'                     => 'array',
        'preview_size'                      => 'medium',
        'insert'                            => 'append',
        'library'                           => 'all',
        'min'                               => '',
        'max'                               => '',
        'min_width'                         => '',
        'min_height'                        => '',
        'min_size'                          => '',
        'max_width'                         => '',
        'max_height'                        => '',
        'max_size'                          => '',
        'mime_types'                        => '',
    ],
    [
        'key'                               => 'field_5f1143fa68e97',
        'label'                             => 'select',
        'name'                              => 'select',
        'type'                              => 'select',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'choices'                           => [],
        'default_value'                     => [],
        'allow_null'                        => 0,
        'multiple'                          => 0,
        'ui'                                => 1,
        'return_format'                     => 'value',
        'ajax'                              => 0,
        'placeholder'                       => '',
    ],
    [
        'key'                               => 'field_5f11440d68e98',
        'label'                             => 'checkbox',
        'name'                              => 'checkbox',
        'type'                              => 'checkbox',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'choices'                           => [],
        'allow_custom'                      => 0,
        'default_value'                     => [],
        'layout'                            => 'vertical',
        'toggle'                            => 0,
        'return_format'                     => 'value',
        'save_custom'                       => 0,
    ],
    [
        'key'                               => 'field_5f11441868e99',
        'label'                             => 'radio',
        'name'                              => 'radio',
        'type'                              => 'radio',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'choices'                           => [],
        'allow_null'                        => 0,
        'other_choice'                      => 0,
        'default_value'                     => '',
        'layout'                            => 'vertical',
        'return_format'                     => 'value',
        'save_other_choice'                 => 0,
    ],
    [
        'key'                               => 'field_5f11443068e9a',
        'label'                             => 'button_group',
        'name'                              => 'button_group',
        'type'                              => 'button_group',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'choices'                           => [],
        'allow_null'                        => 0,
        'default_value'                     => '',
        'layout'                            => 'horizontal',
        'return_format'                     => 'value',
    ],
    [
        'key'                               => 'field_5f11443b68e9b',
        'label'                             => 'boolean',
        'name'                              => 'boolean',
        'type'                              => 'true_false',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'message'                           => '',
        'default_value'                     => 0,
        'ui'                                => 1,
        'ui_on_text'                        => '',
        'ui_off_text'                       => '',
    ],
    [
        'key'                               => 'field_5f11444968e9c',
        'label'                             => 'link',
        'name'                              => 'link',
        'type'                              => 'link',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'return_format'                     => 'array',
    ],
    [
        'key'                               => 'field_5f11446368e9d',
        'label'                             => 'post',
        'name'                              => 'post',
        'type'                              => 'post_object',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'post_type'                         => '',
        'taxonomy'                          => '',
        'allow_null'                        => 0,
        'multiple'                          => 0,
        'return_format'                     => 'object',
        'ui'                                => 1,
    ],
    [
        'key'                               => 'field_5f11446968e9e',
        'label'                             => 'page',
        'name'                              => 'page',
        'type'                              => 'page_link',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'post_type'                         => '',
        'taxonomy'                          => '',
        'allow_null'                        => 0,
        'allow_archives'                    => 1,
        'multiple'                          => 0,
    ],
    [
        'key'                               => 'field_5f11447768e9f',
        'label'                             => 'relationship',
        'name'                              => 'relationship',
        'type'                              => 'relationship',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'post_type'                         => '',
        'taxonomy'                          => '',
        'filters'                           => [
                                                    0 => 'search',
                                                    1 => 'post_type',
                                                    2 => 'taxonomy',
                                               ],
        'elements'                          => '',
        'min'                               => '',
        'max'                               => '',
        'return_format'                     => 'object',
    ],
    [
        'key'                               => 'field_5f11448568ea0',
        'label'                             => 'taxonomy',
        'name'                              => 'taxonomy',
        'type'                              => 'taxonomy',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'taxonomy'                          => 'category',
        'field_type'                        => 'checkbox',
        'add_term'                          => 1,
        'save_terms'                        => 0,
        'load_terms'                        => 0,
        'return_format'                     => 'id',
        'multiple'                          => 0,
        'allow_null'                        => 0,
    ],
    [
        'key'                               => 'field_5f11449068ea1',
        'label'                             => 'user',
        'name'                              => 'user',
        'type'                              => 'user',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'role'                              => '',
        'allow_null'                        => 0,
        'multiple'                          => 0,
        'return_format'                     => 'array',
    ],
    [
        'key'                               => 'field_5f11449b68ea2',
        'label'                             => 'google_map',
        'name'                              => 'google_map',
        'type'                              => 'google_map',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'center_lat'                        => '',
        'center_lng'                        => '',
        'zoom'                              => '',
        'height'                            => '',
    ],
    [
        'key'                               => 'field_5f1144ab68ea3',
        'label'                             => 'date_picker',
        'name'                              => 'date_picker',
        'type'                              => 'date_picker',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'display_format'                    => 'd/m/Y',
        'return_format'                     => 'd/m/Y',
        'first_day'                         => 1,
    ],
    [
        'key'                               => 'field_5f1144b968ea4',
        'label'                             => 'date_time_picker',
        'name'                              => 'date_time_picker',
        'type'                              => 'date_time_picker',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'display_format'                    => 'd/m/Y g:i a',
        'return_format'                     => 'd/m/Y g:i a',
        'first_day'                         => 1,
    ],
    [
        'key'                               => 'field_5f1144c768ea5',
        'label'                             => 'time_picker',
        'name'                              => 'time_picker',
        'type'                              => 'time_picker',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'display_format'                    => 'g:i a',
        'return_format'                     => 'g:i a',
    ],
    [
        'key'                               => 'field_5f1144d368ea6',
        'label'                             => 'color_picker',
        'name'                              => 'color_picker',
        'type'                              => 'color_picker',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'default_value'                     => '',
    ],
    [
        'key'                               => 'field_5f1144df68ea7',
        'label'                             => 'message',
        'name'                              => 'message',
        'type'                              => 'message',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'message'                           => '',
        'new_lines'                         => 'wpautop',
        'esc_html'                          => 0,
    ],
    [
        'key'                               => 'field_5f1144ee68ea8',
        'label'                             => 'accordion',
        'name'                              => 'accordion',
        'type'                              => 'accordion',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'open'                              => 0,
        'multi_expand'                      => 0,
        'endpoint'                          => 0,
    ],
    [
        'key'                               => 'field_5f1144f768ea9',
        'label'                             => 'tab',
        'name'                              => 'tab',
        'type'                              => 'tab',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'placement'                         => 'top',
        'endpoint'                          => 0,
    ],
    [
        'key'                               => 'field_5f11450368eaa',
        'label'                             => 'group',
        'name'                              => 'group',
        'type'                              => 'group',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'layout'                            => 'block',
        'sub_fields'                        => [],
    ],
    [
        'key'                               => 'field_5f11450d68eab',
        'label'                             => 'repeater',
        'name'                              => 'repeater',
        'type'                              => 'repeater',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'collapsed'                         => '',
        'min'                               => 0,
        'max'                               => 0,
        'layout'                            => 'table',
        'button_label'                      => '',
        'sub_fields'                        => [],
    ],
    [
        'key'                               => 'field_5f11451d68eac',
        'label'                             => 'flexible_content',
        'name'                              => 'flexible_content',
        'type'                              => 'flexible_content',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'button_label'                      => 'Add Row',
        'min'                               => '',
        'max'                               => '',
    ],
    [
        'key'                               => 'field_5f11452768ead',
        'label'                             => 'clone',
        'name'                              => 'clone',
        'type'                              => 'clone',
        'instructions'                      => '',
        'required'                          => 0,
        'conditional_logic'                 => 0,
        'clone'                             => '',
        'display'                           => 'seamless',
        'layout'                            => 'block',
        'prefix_label'                      => 0,
        'prefix_name'                       => 0,
    ],
];

